repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: # arguments to configure black 
       - --line-length=89
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: # arguments to configure flake8
       - "--max-line-length=89"
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
